### ISSUE TITLE
Latest PDDI cannot support latest iPad mini (A17 Pro, WiFi|Cellular)

### ISSUE THREAD

**Issue by lstarboy** [doronz88/DeveloperDiskImage#11]
I have a iPad mini(A17 Pro, WiFi), but cannot mount image automatically. I noticed the two new iPad minis' product type are iPad16,1, iPad16,2, and their HardwareModel, BoardId, ChipId are  the following:
	{"iPad16,1", "j410ap", 0x08, 0x8130, "iPad mini (A17 Pro, WiFi)"},
	{"iPad16,2", "j411ap", 0x0A, 0x8130, "iPad mini (A17 Pro, Cellular)"}

**Comment by doronz88** [comment]
Create to submit a PR adding these?

**Comment by doronz88** [comment]
nvm, found out it was published with the latest xcode 16.1
thanks for the heads up!

**Comment by lstarboy** [comment]
> nvm, found out it was published with the latest xcode 16.1 thanks for the heads up!

How to get or make Xcode_iOS_DDI_Personalized myself?

**Comment by vadim-a-yegorov** [comment]
> /Library/Developer/CoreDevice/CandidateDDIs/iOS_DDI.dmg

I am trying to update [Jitterbug](https://github.com/osy/Jitterbug) to support iOS 17, specifically I am closng the issue [#92](https://github.com/osy/Jitterbug/issues/92)

I am missing .signature file, is it possible to derive it from Xcode or should we only use .trustcache from now on? Is .trustcache temporary and has to be regenerated on every iOS reboot? Is .trustcache file possible to generate locally on device?

Since you have more knowledge on the subject, can you please suggest, if Jitterbug can theoretically be implemented without the need for PDDI anymore, through RSD if we will switch from libimobiledevice to pymobiledevice3 ?

**Comment by doronz88** [comment]
The new DDI is a Cryptex software update. There is no `.signature` file any longer. I'm not familiar with jitterbug, but in general you can have JIT with the new DDI mounted by accessing the `debugserver`.
